// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wypozyczalnia_sprzetu_budowlanego.Models;

namespace Wypozyczalnia_sprzetu_budowlanego.Migrations
{
    [DbContext(typeof(baza_sprzetContext))]
    partial class baza_sprzetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wypozyczalnia_sprzetu_budowlanego.Models.Category", b =>
                {
                    b.Property<int>("IdCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_category")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazwaKategorii")
                        .IsRequired()
                        .HasColumnName("nazwa_kategorii")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdCategory")
                        .HasName("PK__Category__E548B6731A0F7ED2");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Wypozyczalnia_sprzetu_budowlanego.Models.Customer", b =>
                {
                    b.Property<int>("IdCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_customer")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnName("imie")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnName("nazwisko")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("NumerTel")
                        .IsRequired()
                        .HasColumnName("numer_tel")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdCustomer")
                        .HasName("PK__Customer__8CC9BA460F14A790");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Wypozyczalnia_sprzetu_budowlanego.Models.Renting", b =>
                {
                    b.Property<int>("IdRenting")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_renting")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnName("customer_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnName("data")
                        .HasColumnType("date");

                    b.Property<int>("ToolId")
                        .HasColumnName("tool_id")
                        .HasColumnType("int");

                    b.HasKey("IdRenting")
                        .HasName("PK__Renting__5B9FC36716996CE5");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ToolId");

                    b.ToTable("Renting");
                });

            modelBuilder.Entity("Wypozyczalnia_sprzetu_budowlanego.Models.Tool", b =>
                {
                    b.Property<int>("IdTool")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_tool")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnName("category_id")
                        .HasColumnType("int");

                    b.Property<int>("Cena")
                        .HasColumnName("cena")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("model")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnName("nazwa")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Producent")
                        .IsRequired()
                        .HasColumnName("producent")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("IdTool")
                        .HasName("PK__Tool__C9346C347522EEAE");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tool");
                });

            modelBuilder.Entity("Wypozyczalnia_sprzetu_budowlanego.Models.Renting", b =>
                {
                    b.HasOne("Wypozyczalnia_sprzetu_budowlanego.Models.Customer", "Customer")
                        .WithMany("Renting")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Renting_ToCustomer")
                        .IsRequired();

                    b.HasOne("Wypozyczalnia_sprzetu_budowlanego.Models.Tool", "Tool")
                        .WithMany("Renting")
                        .HasForeignKey("ToolId")
                        .HasConstraintName("FK_Renting_ToTool")
                        .IsRequired();
                });

            modelBuilder.Entity("Wypozyczalnia_sprzetu_budowlanego.Models.Tool", b =>
                {
                    b.HasOne("Wypozyczalnia_sprzetu_budowlanego.Models.Category", "Category")
                        .WithMany("Tool")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Tool_ToCategoty")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
